---
title: "COVID-19 Forecast Similarity Analysis"
author: "Nutcha Wattanachit, Johannes Bracher, Evan Ray, Nick Reich"
date: "10/10/2022"
header-includes:
   - \usepackage{tabularx}
   - \usepackage{hyperref}
   - \usepackage{wrapfig}
   - \usepackage{float}
   - \usepackage{colortbl}
   - \usepackage{pdflscape}
   - \usepackage{tabu}
   - \usepackage{xcolor}
output:
  pdf_document:
        latex_engine: xelatex
        fig_caption: yes
        keep_tex: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(energy)
library(knitr)
library(data.table)
library(covidHubUtils)
library(RColorBrewer)
#devtools::install_github("reichlab/covidHubUtils",force=TRUE)
library(lubridate)
library(zoltr)
# devtools::install_github("reichlab/zoltr",force=TRUE)
library(igraph)
library(gtools)
library(gtable)
library(gridExtra)
library(grid)
library(ggdendro)
library(forecast)
library(gridGraphics)
knitr::opts_chunk$set(echo=FALSE, comment = FALSE, message=FALSE, 
                      # fig.show= 'hold',fig.pos="H",table.placement="H",
                      fig.show= 'hold',table.placement="H",
                      warning =FALSE)
```

```{r hosp_dat, out.width="100%",out.height="100%",fig.height=6}
inc_hosp_targets <- paste(0:130, "day ahead inc hosp")
forecasts_hosp <- load_forecasts(
  models = "COVIDhub-baseline",
  dates = c("2021-03-29","2022-01-17","2022-08-14"),
  date_window_size = 6,
  locations = "25",
  types = c("point", "quantile"),
  targets = inc_hosp_targets,
  source = "zoltar",
  verbose = FALSE,
  as_of = NULL,
  hub = c("US")
)
p_hosp <- plot_forecasts(
  forecast_data = forecasts_hosp,
  truth_source = "HealthData",
  target_variable = "inc hosp",
  intervals = c(.5, .8, .95)
)
p_hosp2 <- p_hosp +
  scale_x_date(name=NULL, date_breaks = "3 months", date_labels = "%b-%y",
               limits = c(as.Date("2021-02-01"), as.Date("2022-09-27")))+
  theme_bw()+
  theme(axis.text.x = element_text(size=7),
        legend.position = "bottom",
        legend.box = 'vertical') 
p_hosp2
```


